name: featuresyrup-docs
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - pandas
  - numpy
  - rdkit
  - networkx
  - matplotlib
  - plotly
  - pyyaml
  - tqdm
  - psutil
  - regex
  - setuptools
  - setuptools-scm
  - versioningit
  - morfeus
  - dscribe
  - sphinx
  - sphinx-rtd-theme
  - sphinx-autodoc-typehints
  - sphinx-design
  - sphinx-copybutton
  - myst-parser
  - pip:
      - torch
      - torch-geometric

